using System;
using System.Threading.Tasks;
using Azure;
using Azure.Core;
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.Dns;
using Azure.ResourceManager.Dns.Models;
using Azure.ResourceManager.FrontDoor;
using Azure.ResourceManager.FrontDoor.Models;
using Azure.Cosmos;
using dotnet5.Models;
using Microsoft.Extensions.Configuration;

namespace dotnet5
{
    public class StaticSiteProvisioningService
    {
        private readonly ArmClient _armClient;
        private readonly CosmosClient _cosmosClient;
        private readonly string _subscriptionId;
        private readonly string _resourceGroup;
        private readonly string _frontDoorName;
        private readonly string _dnsZoneName;
        private readonly string _cosmosDatabase;
        private readonly string _cosmosContainer;

        public StaticSiteProvisioningService(IConfiguration configuration)
        {
            _armClient = new ArmClient(new DefaultAzureCredential());
            _cosmosClient = new CosmosClient(configuration["CosmosEndpoint"], configuration["CosmosKey"]);
            _subscriptionId = configuration["SubscriptionId"] ?? string.Empty;
            _resourceGroup = configuration["ResourceGroup"] ?? string.Empty;
            _frontDoorName = configuration["FrontDoorName"] ?? string.Empty;
            _dnsZoneName = configuration["DnsZoneName"] ?? string.Empty;
            _cosmosDatabase = configuration["CosmosDatabase"] ?? "staticsites";
            _cosmosContainer = configuration["CosmosContainer"] ?? "sites";
        }

        public async Task<string> ProvisionStaticSiteAsync(StaticSiteRequest request)
        {
            // Create endpoint under existing Front Door profile
            var profileId = FrontDoorProfileResource.CreateResourceIdentifier(_subscriptionId, _resourceGroup, _frontDoorName);
            FrontDoorProfileResource profile = _armClient.GetFrontDoorProfileResource(profileId);

            var endpointCollection = profile.GetFrontDoorEndpoints();
            var endpointData = new FrontDoorEndpointData
            {
                EnabledState = FrontDoorEndpointEnabledState.Enabled,
                AutoGeneratedDomainNameLabelScope = FrontDoorEndpointAutoGeneratedDomainNameLabelScope.Endpoint
            };
            ArmOperation<FrontDoorEndpointResource> endpointOp = await endpointCollection.CreateOrUpdateAsync(WaitUntil.Completed, request.Slug, endpointData);
            FrontDoorEndpointResource endpoint = endpointOp.Value;

            // Create origin group
            var originGroups = profile.GetFrontDoorOriginGroups();
            var ogName = $"{request.Slug}-origin-group";
            var originGroupData = new FrontDoorOriginGroupData
            {
                SessionAffinityState = FrontDoorState.Disabled
            };
            var originGroup = await originGroups.CreateOrUpdateAsync(WaitUntil.Completed, ogName, originGroupData);

            // Create route
            var routes = endpoint.GetFrontDoorRoutes();
            var routeData = new FrontDoorRouteData
            {
                OriginGroup = new WritableSubResource { Id = originGroup.Value.Id },
                PatternsToMatch = { "/*" },
                SupportedProtocols = { FrontDoorEndpointSupportedProtocol.Https },
                CachingEnabled = false
            };
            await routes.CreateOrUpdateAsync(WaitUntil.Completed, $"{request.Slug}-default-route", routeData);

            // DNS CNAME record
            var dnsZoneId = DnsZoneResource.CreateResourceIdentifier(_subscriptionId, _resourceGroup, _dnsZoneName);
            DnsZoneResource dnsZone = _armClient.GetDnsZoneResource(dnsZoneId);
            var cnameRecords = dnsZone.GetDnsCnameRecords();
            var cnameData = new DnsCnameRecordData { Cname = endpoint.Data.HostName };
            await cnameRecords.CreateOrUpdateAsync(WaitUntil.Completed, request.Slug, cnameData);

            // Add custom domain to endpoint
            var domains = profile.GetFrontDoorCustomDomains();
            var domainData = new FrontDoorCustomDomainData
            {
                HostName = $"{request.Slug}.{_dnsZoneName}"
            };
            var domain = await domains.CreateOrUpdateAsync(WaitUntil.Completed, request.Slug, domainData);
            await endpoint.AddCustomDomainAsync(domain.Value);

            // Store reference in Cosmos DB
            var container = _cosmosClient.GetContainer(_cosmosDatabase, _cosmosContainer);
            await container.UpsertItemAsync(new
            {
                id = Guid.NewGuid().ToString(),
                tenant = request.TenantId,
                user = request.UserId,
                workspace = request.WorkspaceId,
                slug = request.Slug,
                endpointId = endpoint.Id,
                originGroupId = originGroup.Value.Id,
                customDomainId = domain.Value.Id
            });

            return $"https://{request.Slug}.{_dnsZoneName}";
        }
    }
}
